package cn.longzzai.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class BookDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_detail.book_detail_id
     *
     * @mbggenerated
     */
    private int bookDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_detail.book_id
     *
     * @mbggenerated
     */
    private String bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_detail.book_title
     *
     * @mbggenerated
     */
    private String bookTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_detail.book_author
     *
     * @mbggenerated
     */
    private String bookAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_detail.book_intro
     *
     * @mbggenerated
     */
    private String bookIntro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_detail.book_cover
     *
     * @mbggenerated
     */
    private String bookCover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_detail.major_cate_name
     *
     * @mbggenerated
     */
    private String majorCateName = "未分类";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_detail.minor_cate_name
     *
     * @mbggenerated
     */
    private String minorCateName = "未分类";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_detail.lately_follower
     *
     * @mbggenerated
     */
    private Long latelyFollower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_detail.retention_ratio
     *
     * @mbggenerated
     */
    private BigDecimal retentionRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_detail.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_detail.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_detail.is_serial
     *
     * @mbggenerated
     */
    private Boolean isSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_detail.last_chapter
     *
     * @mbggenerated
     */
    private String lastChapter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_detail.word_count
     *
     * @mbggenerated
     */
    private Long wordCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_detail.click_number
     *
     * @mbggenerated
     */
    private Long clickNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_detail.add_rack
     *
     * @mbggenerated
     */
    private Long addRack;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_detail.book_detail_id
     *
     * @return the value of book_detail.book_detail_id
     *
     * @mbggenerated
     */
    public int getBookDetailId() {
        return bookDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_detail.book_detail_id
     *
     * @param bookDetailId the value for book_detail.book_detail_id
     *
     * @mbggenerated
     */
    public void setBookDetailId(int bookDetailId) {
        this.bookDetailId = bookDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_detail.book_id
     *
     * @return the value of book_detail.book_id
     *
     * @mbggenerated
     */
    public String getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_detail.book_id
     *
     * @param bookId the value for book_detail.book_id
     *
     * @mbggenerated
     */
    public void setBookId(String bookId) {
        this.bookId = bookId == null ? null : bookId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_detail.book_title
     *
     * @return the value of book_detail.book_title
     *
     * @mbggenerated
     */
    public String getBookTitle() {
        return bookTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_detail.book_title
     *
     * @param bookTitle the value for book_detail.book_title
     *
     * @mbggenerated
     */
    public void setBookTitle(String bookTitle) {
        this.bookTitle = bookTitle == null ? null : bookTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_detail.book_author
     *
     * @return the value of book_detail.book_author
     *
     * @mbggenerated
     */
    public String getBookAuthor() {
        return bookAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_detail.book_author
     *
     * @param bookAuthor the value for book_detail.book_author
     *
     * @mbggenerated
     */
    public void setBookAuthor(String bookAuthor) {
        this.bookAuthor = bookAuthor == null ? null : bookAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_detail.book_intro
     *
     * @return the value of book_detail.book_intro
     *
     * @mbggenerated
     */
    public String getBookIntro() {
        return bookIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_detail.book_intro
     *
     * @param bookIntro the value for book_detail.book_intro
     *
     * @mbggenerated
     */
    public void setBookIntro(String bookIntro) {
        this.bookIntro = bookIntro == null ? null : bookIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_detail.book_cover
     *
     * @return the value of book_detail.book_cover
     *
     * @mbggenerated
     */
    public String getBookCover() {
        return bookCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_detail.book_cover
     *
     * @param bookCover the value for book_detail.book_cover
     *
     * @mbggenerated
     */
    public void setBookCover(String bookCover) {
        this.bookCover = bookCover == null ? null : bookCover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_detail.major_cate_name
     *
     * @return the value of book_detail.major_cate_name
     *
     * @mbggenerated
     */
    public String getMajorCateName() {
        return majorCateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_detail.major_cate_name
     *
     * @param majorCateName the value for book_detail.major_cate_name
     *
     * @mbggenerated
     */
    public void setMajorCateName(String majorCateName) {
        this.majorCateName = majorCateName == null ? null : majorCateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_detail.minor_cate_name
     *
     * @return the value of book_detail.minor_cate_name
     *
     * @mbggenerated
     */
    public String getMinorCateName() {
        return minorCateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_detail.minor_cate_name
     *
     * @param minorCateName the value for book_detail.minor_cate_name
     *
     * @mbggenerated
     */
    public void setMinorCateName(String minorCateName) {
        this.minorCateName = minorCateName == null ? null : minorCateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_detail.lately_follower
     *
     * @return the value of book_detail.lately_follower
     *
     * @mbggenerated
     */
    public Long getLatelyFollower() {
        return latelyFollower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_detail.lately_follower
     *
     * @param latelyFollower the value for book_detail.lately_follower
     *
     * @mbggenerated
     */
    public void setLatelyFollower(Long latelyFollower) {
        this.latelyFollower = latelyFollower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_detail.retention_ratio
     *
     * @return the value of book_detail.retention_ratio
     *
     * @mbggenerated
     */
    public BigDecimal getRetentionRatio() {
        return retentionRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_detail.retention_ratio
     *
     * @param retentionRatio the value for book_detail.retention_ratio
     *
     * @mbggenerated
     */
    public void setRetentionRatio(BigDecimal retentionRatio) {
        this.retentionRatio = retentionRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_detail.create_time
     *
     * @return the value of book_detail.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_detail.create_time
     *
     * @param createTime the value for book_detail.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_detail.update_time
     *
     * @return the value of book_detail.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_detail.update_time
     *
     * @param updateTime the value for book_detail.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_detail.is_serial
     *
     * @return the value of book_detail.is_serial
     *
     * @mbggenerated
     */
    public Boolean getIsSerial() {
        return isSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_detail.is_serial
     *
     * @param isSerial the value for book_detail.is_serial
     *
     * @mbggenerated
     */
    public void setIsSerial(Boolean isSerial) {
        this.isSerial = isSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_detail.last_chapter
     *
     * @return the value of book_detail.last_chapter
     *
     * @mbggenerated
     */
    public String getLastChapter() {
        return lastChapter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_detail.last_chapter
     *
     * @param lastChapter the value for book_detail.last_chapter
     *
     * @mbggenerated
     */
    public void setLastChapter(String lastChapter) {
        this.lastChapter = lastChapter == null ? null : lastChapter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_detail.word_count
     *
     * @return the value of book_detail.word_count
     *
     * @mbggenerated
     */
    public Long getWordCount() {
        return wordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_detail.word_count
     *
     * @param wordCount the value for book_detail.word_count
     *
     * @mbggenerated
     */
    public void setWordCount(Long wordCount) {
        this.wordCount = wordCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_detail.click_number
     *
     * @return the value of book_detail.click_number
     *
     * @mbggenerated
     */
    public Long getClickNumber() {
        return clickNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_detail.click_number
     *
     * @param clickNumber the value for book_detail.click_number
     *
     * @mbggenerated
     */
    public void setClickNumber(Long clickNumber) {
        this.clickNumber = clickNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_detail.add_rack
     *
     * @return the value of book_detail.add_rack
     *
     * @mbggenerated
     */
    public Long getAddRack() {
        return addRack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_detail.add_rack
     *
     * @param addRack the value for book_detail.add_rack
     *
     * @mbggenerated
     */
    public void setAddRack(Long addRack) {
        this.addRack = addRack;
    }
}