package cn.longzzai.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BookDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_detail
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_detail
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_detail
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_detail
     *
     * @mbggenerated
     */
    public BookDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_detail
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_detail
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_detail
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_detail
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_detail
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_detail
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_detail
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_detail
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_detail
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_detail
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_detail
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBookDetailIdIsNull() {
            addCriterion("book_detail_id is null");
            return (Criteria) this;
        }

        public Criteria andBookDetailIdIsNotNull() {
            addCriterion("book_detail_id is not null");
            return (Criteria) this;
        }

        public Criteria andBookDetailIdEqualTo(Long value) {
            addCriterion("book_detail_id =", value, "bookDetailId");
            return (Criteria) this;
        }

        public Criteria andBookDetailIdNotEqualTo(Long value) {
            addCriterion("book_detail_id <>", value, "bookDetailId");
            return (Criteria) this;
        }

        public Criteria andBookDetailIdGreaterThan(Long value) {
            addCriterion("book_detail_id >", value, "bookDetailId");
            return (Criteria) this;
        }

        public Criteria andBookDetailIdGreaterThanOrEqualTo(Long value) {
            addCriterion("book_detail_id >=", value, "bookDetailId");
            return (Criteria) this;
        }

        public Criteria andBookDetailIdLessThan(Long value) {
            addCriterion("book_detail_id <", value, "bookDetailId");
            return (Criteria) this;
        }

        public Criteria andBookDetailIdLessThanOrEqualTo(Long value) {
            addCriterion("book_detail_id <=", value, "bookDetailId");
            return (Criteria) this;
        }

        public Criteria andBookDetailIdIn(List<Long> values) {
            addCriterion("book_detail_id in", values, "bookDetailId");
            return (Criteria) this;
        }

        public Criteria andBookDetailIdNotIn(List<Long> values) {
            addCriterion("book_detail_id not in", values, "bookDetailId");
            return (Criteria) this;
        }

        public Criteria andBookDetailIdBetween(Long value1, Long value2) {
            addCriterion("book_detail_id between", value1, value2, "bookDetailId");
            return (Criteria) this;
        }

        public Criteria andBookDetailIdNotBetween(Long value1, Long value2) {
            addCriterion("book_detail_id not between", value1, value2, "bookDetailId");
            return (Criteria) this;
        }

        public Criteria andBookIdIsNull() {
            addCriterion("book_id is null");
            return (Criteria) this;
        }

        public Criteria andBookIdIsNotNull() {
            addCriterion("book_id is not null");
            return (Criteria) this;
        }

        public Criteria andBookIdEqualTo(String value) {
            addCriterion("book_id =", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotEqualTo(String value) {
            addCriterion("book_id <>", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdGreaterThan(String value) {
            addCriterion("book_id >", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdGreaterThanOrEqualTo(String value) {
            addCriterion("book_id >=", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdLessThan(String value) {
            addCriterion("book_id <", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdLessThanOrEqualTo(String value) {
            addCriterion("book_id <=", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdLike(String value) {
            addCriterion("book_id like", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotLike(String value) {
            addCriterion("book_id not like", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdIn(List<String> values) {
            addCriterion("book_id in", values, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotIn(List<String> values) {
            addCriterion("book_id not in", values, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdBetween(String value1, String value2) {
            addCriterion("book_id between", value1, value2, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotBetween(String value1, String value2) {
            addCriterion("book_id not between", value1, value2, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookTitleIsNull() {
            addCriterion("book_title is null");
            return (Criteria) this;
        }

        public Criteria andBookTitleIsNotNull() {
            addCriterion("book_title is not null");
            return (Criteria) this;
        }

        public Criteria andBookTitleEqualTo(String value) {
            addCriterion("book_title =", value, "bookTitle");
            return (Criteria) this;
        }

        public Criteria andBookTitleNotEqualTo(String value) {
            addCriterion("book_title <>", value, "bookTitle");
            return (Criteria) this;
        }

        public Criteria andBookTitleGreaterThan(String value) {
            addCriterion("book_title >", value, "bookTitle");
            return (Criteria) this;
        }

        public Criteria andBookTitleGreaterThanOrEqualTo(String value) {
            addCriterion("book_title >=", value, "bookTitle");
            return (Criteria) this;
        }

        public Criteria andBookTitleLessThan(String value) {
            addCriterion("book_title <", value, "bookTitle");
            return (Criteria) this;
        }

        public Criteria andBookTitleLessThanOrEqualTo(String value) {
            addCriterion("book_title <=", value, "bookTitle");
            return (Criteria) this;
        }

        public Criteria andBookTitleLike(String value) {
            addCriterion("book_title like", value, "bookTitle");
            return (Criteria) this;
        }

        public Criteria andBookTitleNotLike(String value) {
            addCriterion("book_title not like", value, "bookTitle");
            return (Criteria) this;
        }

        public Criteria andBookTitleIn(List<String> values) {
            addCriterion("book_title in", values, "bookTitle");
            return (Criteria) this;
        }

        public Criteria andBookTitleNotIn(List<String> values) {
            addCriterion("book_title not in", values, "bookTitle");
            return (Criteria) this;
        }

        public Criteria andBookTitleBetween(String value1, String value2) {
            addCriterion("book_title between", value1, value2, "bookTitle");
            return (Criteria) this;
        }

        public Criteria andBookTitleNotBetween(String value1, String value2) {
            addCriterion("book_title not between", value1, value2, "bookTitle");
            return (Criteria) this;
        }

        public Criteria andBookAuthorIsNull() {
            addCriterion("book_author is null");
            return (Criteria) this;
        }

        public Criteria andBookAuthorIsNotNull() {
            addCriterion("book_author is not null");
            return (Criteria) this;
        }

        public Criteria andBookAuthorEqualTo(String value) {
            addCriterion("book_author =", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorNotEqualTo(String value) {
            addCriterion("book_author <>", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorGreaterThan(String value) {
            addCriterion("book_author >", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("book_author >=", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorLessThan(String value) {
            addCriterion("book_author <", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorLessThanOrEqualTo(String value) {
            addCriterion("book_author <=", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorLike(String value) {
            addCriterion("book_author like", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorNotLike(String value) {
            addCriterion("book_author not like", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorIn(List<String> values) {
            addCriterion("book_author in", values, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorNotIn(List<String> values) {
            addCriterion("book_author not in", values, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorBetween(String value1, String value2) {
            addCriterion("book_author between", value1, value2, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorNotBetween(String value1, String value2) {
            addCriterion("book_author not between", value1, value2, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookIntroIsNull() {
            addCriterion("book_intro is null");
            return (Criteria) this;
        }

        public Criteria andBookIntroIsNotNull() {
            addCriterion("book_intro is not null");
            return (Criteria) this;
        }

        public Criteria andBookIntroEqualTo(String value) {
            addCriterion("book_intro =", value, "bookIntro");
            return (Criteria) this;
        }

        public Criteria andBookIntroNotEqualTo(String value) {
            addCriterion("book_intro <>", value, "bookIntro");
            return (Criteria) this;
        }

        public Criteria andBookIntroGreaterThan(String value) {
            addCriterion("book_intro >", value, "bookIntro");
            return (Criteria) this;
        }

        public Criteria andBookIntroGreaterThanOrEqualTo(String value) {
            addCriterion("book_intro >=", value, "bookIntro");
            return (Criteria) this;
        }

        public Criteria andBookIntroLessThan(String value) {
            addCriterion("book_intro <", value, "bookIntro");
            return (Criteria) this;
        }

        public Criteria andBookIntroLessThanOrEqualTo(String value) {
            addCriterion("book_intro <=", value, "bookIntro");
            return (Criteria) this;
        }

        public Criteria andBookIntroLike(String value) {
            addCriterion("book_intro like", value, "bookIntro");
            return (Criteria) this;
        }

        public Criteria andBookIntroNotLike(String value) {
            addCriterion("book_intro not like", value, "bookIntro");
            return (Criteria) this;
        }

        public Criteria andBookIntroIn(List<String> values) {
            addCriterion("book_intro in", values, "bookIntro");
            return (Criteria) this;
        }

        public Criteria andBookIntroNotIn(List<String> values) {
            addCriterion("book_intro not in", values, "bookIntro");
            return (Criteria) this;
        }

        public Criteria andBookIntroBetween(String value1, String value2) {
            addCriterion("book_intro between", value1, value2, "bookIntro");
            return (Criteria) this;
        }

        public Criteria andBookIntroNotBetween(String value1, String value2) {
            addCriterion("book_intro not between", value1, value2, "bookIntro");
            return (Criteria) this;
        }

        public Criteria andBookCoverIsNull() {
            addCriterion("book_cover is null");
            return (Criteria) this;
        }

        public Criteria andBookCoverIsNotNull() {
            addCriterion("book_cover is not null");
            return (Criteria) this;
        }

        public Criteria andBookCoverEqualTo(String value) {
            addCriterion("book_cover =", value, "bookCover");
            return (Criteria) this;
        }

        public Criteria andBookCoverNotEqualTo(String value) {
            addCriterion("book_cover <>", value, "bookCover");
            return (Criteria) this;
        }

        public Criteria andBookCoverGreaterThan(String value) {
            addCriterion("book_cover >", value, "bookCover");
            return (Criteria) this;
        }

        public Criteria andBookCoverGreaterThanOrEqualTo(String value) {
            addCriterion("book_cover >=", value, "bookCover");
            return (Criteria) this;
        }

        public Criteria andBookCoverLessThan(String value) {
            addCriterion("book_cover <", value, "bookCover");
            return (Criteria) this;
        }

        public Criteria andBookCoverLessThanOrEqualTo(String value) {
            addCriterion("book_cover <=", value, "bookCover");
            return (Criteria) this;
        }

        public Criteria andBookCoverLike(String value) {
            addCriterion("book_cover like", value, "bookCover");
            return (Criteria) this;
        }

        public Criteria andBookCoverNotLike(String value) {
            addCriterion("book_cover not like", value, "bookCover");
            return (Criteria) this;
        }

        public Criteria andBookCoverIn(List<String> values) {
            addCriterion("book_cover in", values, "bookCover");
            return (Criteria) this;
        }

        public Criteria andBookCoverNotIn(List<String> values) {
            addCriterion("book_cover not in", values, "bookCover");
            return (Criteria) this;
        }

        public Criteria andBookCoverBetween(String value1, String value2) {
            addCriterion("book_cover between", value1, value2, "bookCover");
            return (Criteria) this;
        }

        public Criteria andBookCoverNotBetween(String value1, String value2) {
            addCriterion("book_cover not between", value1, value2, "bookCover");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameIsNull() {
            addCriterion("major_cate_name is null");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameIsNotNull() {
            addCriterion("major_cate_name is not null");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameEqualTo(String value) {
            addCriterion("major_cate_name =", value, "majorCateName");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameNotEqualTo(String value) {
            addCriterion("major_cate_name <>", value, "majorCateName");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameGreaterThan(String value) {
            addCriterion("major_cate_name >", value, "majorCateName");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameGreaterThanOrEqualTo(String value) {
            addCriterion("major_cate_name >=", value, "majorCateName");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameLessThan(String value) {
            addCriterion("major_cate_name <", value, "majorCateName");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameLessThanOrEqualTo(String value) {
            addCriterion("major_cate_name <=", value, "majorCateName");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameLike(String value) {
            addCriterion("major_cate_name like", value, "majorCateName");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameNotLike(String value) {
            addCriterion("major_cate_name not like", value, "majorCateName");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameIn(List<String> values) {
            addCriterion("major_cate_name in", values, "majorCateName");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameNotIn(List<String> values) {
            addCriterion("major_cate_name not in", values, "majorCateName");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameBetween(String value1, String value2) {
            addCriterion("major_cate_name between", value1, value2, "majorCateName");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameNotBetween(String value1, String value2) {
            addCriterion("major_cate_name not between", value1, value2, "majorCateName");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameIsNull() {
            addCriterion("minor_cate_name is null");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameIsNotNull() {
            addCriterion("minor_cate_name is not null");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameEqualTo(String value) {
            addCriterion("minor_cate_name =", value, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameNotEqualTo(String value) {
            addCriterion("minor_cate_name <>", value, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameGreaterThan(String value) {
            addCriterion("minor_cate_name >", value, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameGreaterThanOrEqualTo(String value) {
            addCriterion("minor_cate_name >=", value, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameLessThan(String value) {
            addCriterion("minor_cate_name <", value, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameLessThanOrEqualTo(String value) {
            addCriterion("minor_cate_name <=", value, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameLike(String value) {
            addCriterion("minor_cate_name like", value, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameNotLike(String value) {
            addCriterion("minor_cate_name not like", value, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameIn(List<String> values) {
            addCriterion("minor_cate_name in", values, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameNotIn(List<String> values) {
            addCriterion("minor_cate_name not in", values, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameBetween(String value1, String value2) {
            addCriterion("minor_cate_name between", value1, value2, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameNotBetween(String value1, String value2) {
            addCriterion("minor_cate_name not between", value1, value2, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andLatelyFollowerIsNull() {
            addCriterion("lately_follower is null");
            return (Criteria) this;
        }

        public Criteria andLatelyFollowerIsNotNull() {
            addCriterion("lately_follower is not null");
            return (Criteria) this;
        }

        public Criteria andLatelyFollowerEqualTo(Long value) {
            addCriterion("lately_follower =", value, "latelyFollower");
            return (Criteria) this;
        }

        public Criteria andLatelyFollowerNotEqualTo(Long value) {
            addCriterion("lately_follower <>", value, "latelyFollower");
            return (Criteria) this;
        }

        public Criteria andLatelyFollowerGreaterThan(Long value) {
            addCriterion("lately_follower >", value, "latelyFollower");
            return (Criteria) this;
        }

        public Criteria andLatelyFollowerGreaterThanOrEqualTo(Long value) {
            addCriterion("lately_follower >=", value, "latelyFollower");
            return (Criteria) this;
        }

        public Criteria andLatelyFollowerLessThan(Long value) {
            addCriterion("lately_follower <", value, "latelyFollower");
            return (Criteria) this;
        }

        public Criteria andLatelyFollowerLessThanOrEqualTo(Long value) {
            addCriterion("lately_follower <=", value, "latelyFollower");
            return (Criteria) this;
        }

        public Criteria andLatelyFollowerIn(List<Long> values) {
            addCriterion("lately_follower in", values, "latelyFollower");
            return (Criteria) this;
        }

        public Criteria andLatelyFollowerNotIn(List<Long> values) {
            addCriterion("lately_follower not in", values, "latelyFollower");
            return (Criteria) this;
        }

        public Criteria andLatelyFollowerBetween(Long value1, Long value2) {
            addCriterion("lately_follower between", value1, value2, "latelyFollower");
            return (Criteria) this;
        }

        public Criteria andLatelyFollowerNotBetween(Long value1, Long value2) {
            addCriterion("lately_follower not between", value1, value2, "latelyFollower");
            return (Criteria) this;
        }

        public Criteria andRetentionRatioIsNull() {
            addCriterion("retention_ratio is null");
            return (Criteria) this;
        }

        public Criteria andRetentionRatioIsNotNull() {
            addCriterion("retention_ratio is not null");
            return (Criteria) this;
        }

        public Criteria andRetentionRatioEqualTo(BigDecimal value) {
            addCriterion("retention_ratio =", value, "retentionRatio");
            return (Criteria) this;
        }

        public Criteria andRetentionRatioNotEqualTo(BigDecimal value) {
            addCriterion("retention_ratio <>", value, "retentionRatio");
            return (Criteria) this;
        }

        public Criteria andRetentionRatioGreaterThan(BigDecimal value) {
            addCriterion("retention_ratio >", value, "retentionRatio");
            return (Criteria) this;
        }

        public Criteria andRetentionRatioGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("retention_ratio >=", value, "retentionRatio");
            return (Criteria) this;
        }

        public Criteria andRetentionRatioLessThan(BigDecimal value) {
            addCriterion("retention_ratio <", value, "retentionRatio");
            return (Criteria) this;
        }

        public Criteria andRetentionRatioLessThanOrEqualTo(BigDecimal value) {
            addCriterion("retention_ratio <=", value, "retentionRatio");
            return (Criteria) this;
        }

        public Criteria andRetentionRatioIn(List<BigDecimal> values) {
            addCriterion("retention_ratio in", values, "retentionRatio");
            return (Criteria) this;
        }

        public Criteria andRetentionRatioNotIn(List<BigDecimal> values) {
            addCriterion("retention_ratio not in", values, "retentionRatio");
            return (Criteria) this;
        }

        public Criteria andRetentionRatioBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("retention_ratio between", value1, value2, "retentionRatio");
            return (Criteria) this;
        }

        public Criteria andRetentionRatioNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("retention_ratio not between", value1, value2, "retentionRatio");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andIsSerialIsNull() {
            addCriterion("is_serial is null");
            return (Criteria) this;
        }

        public Criteria andIsSerialIsNotNull() {
            addCriterion("is_serial is not null");
            return (Criteria) this;
        }

        public Criteria andIsSerialEqualTo(Boolean value) {
            addCriterion("is_serial =", value, "isSerial");
            return (Criteria) this;
        }

        public Criteria andIsSerialNotEqualTo(Boolean value) {
            addCriterion("is_serial <>", value, "isSerial");
            return (Criteria) this;
        }

        public Criteria andIsSerialGreaterThan(Boolean value) {
            addCriterion("is_serial >", value, "isSerial");
            return (Criteria) this;
        }

        public Criteria andIsSerialGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_serial >=", value, "isSerial");
            return (Criteria) this;
        }

        public Criteria andIsSerialLessThan(Boolean value) {
            addCriterion("is_serial <", value, "isSerial");
            return (Criteria) this;
        }

        public Criteria andIsSerialLessThanOrEqualTo(Boolean value) {
            addCriterion("is_serial <=", value, "isSerial");
            return (Criteria) this;
        }

        public Criteria andIsSerialIn(List<Boolean> values) {
            addCriterion("is_serial in", values, "isSerial");
            return (Criteria) this;
        }

        public Criteria andIsSerialNotIn(List<Boolean> values) {
            addCriterion("is_serial not in", values, "isSerial");
            return (Criteria) this;
        }

        public Criteria andIsSerialBetween(Boolean value1, Boolean value2) {
            addCriterion("is_serial between", value1, value2, "isSerial");
            return (Criteria) this;
        }

        public Criteria andIsSerialNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_serial not between", value1, value2, "isSerial");
            return (Criteria) this;
        }

        public Criteria andLastChapterIsNull() {
            addCriterion("last_chapter is null");
            return (Criteria) this;
        }

        public Criteria andLastChapterIsNotNull() {
            addCriterion("last_chapter is not null");
            return (Criteria) this;
        }

        public Criteria andLastChapterEqualTo(String value) {
            addCriterion("last_chapter =", value, "lastChapter");
            return (Criteria) this;
        }

        public Criteria andLastChapterNotEqualTo(String value) {
            addCriterion("last_chapter <>", value, "lastChapter");
            return (Criteria) this;
        }

        public Criteria andLastChapterGreaterThan(String value) {
            addCriterion("last_chapter >", value, "lastChapter");
            return (Criteria) this;
        }

        public Criteria andLastChapterGreaterThanOrEqualTo(String value) {
            addCriterion("last_chapter >=", value, "lastChapter");
            return (Criteria) this;
        }

        public Criteria andLastChapterLessThan(String value) {
            addCriterion("last_chapter <", value, "lastChapter");
            return (Criteria) this;
        }

        public Criteria andLastChapterLessThanOrEqualTo(String value) {
            addCriterion("last_chapter <=", value, "lastChapter");
            return (Criteria) this;
        }

        public Criteria andLastChapterLike(String value) {
            addCriterion("last_chapter like", value, "lastChapter");
            return (Criteria) this;
        }

        public Criteria andLastChapterNotLike(String value) {
            addCriterion("last_chapter not like", value, "lastChapter");
            return (Criteria) this;
        }

        public Criteria andLastChapterIn(List<String> values) {
            addCriterion("last_chapter in", values, "lastChapter");
            return (Criteria) this;
        }

        public Criteria andLastChapterNotIn(List<String> values) {
            addCriterion("last_chapter not in", values, "lastChapter");
            return (Criteria) this;
        }

        public Criteria andLastChapterBetween(String value1, String value2) {
            addCriterion("last_chapter between", value1, value2, "lastChapter");
            return (Criteria) this;
        }

        public Criteria andLastChapterNotBetween(String value1, String value2) {
            addCriterion("last_chapter not between", value1, value2, "lastChapter");
            return (Criteria) this;
        }

        public Criteria andWordCountIsNull() {
            addCriterion("word_count is null");
            return (Criteria) this;
        }

        public Criteria andWordCountIsNotNull() {
            addCriterion("word_count is not null");
            return (Criteria) this;
        }

        public Criteria andWordCountEqualTo(Long value) {
            addCriterion("word_count =", value, "wordCount");
            return (Criteria) this;
        }

        public Criteria andWordCountNotEqualTo(Long value) {
            addCriterion("word_count <>", value, "wordCount");
            return (Criteria) this;
        }

        public Criteria andWordCountGreaterThan(Long value) {
            addCriterion("word_count >", value, "wordCount");
            return (Criteria) this;
        }

        public Criteria andWordCountGreaterThanOrEqualTo(Long value) {
            addCriterion("word_count >=", value, "wordCount");
            return (Criteria) this;
        }

        public Criteria andWordCountLessThan(Long value) {
            addCriterion("word_count <", value, "wordCount");
            return (Criteria) this;
        }

        public Criteria andWordCountLessThanOrEqualTo(Long value) {
            addCriterion("word_count <=", value, "wordCount");
            return (Criteria) this;
        }

        public Criteria andWordCountIn(List<Long> values) {
            addCriterion("word_count in", values, "wordCount");
            return (Criteria) this;
        }

        public Criteria andWordCountNotIn(List<Long> values) {
            addCriterion("word_count not in", values, "wordCount");
            return (Criteria) this;
        }

        public Criteria andWordCountBetween(Long value1, Long value2) {
            addCriterion("word_count between", value1, value2, "wordCount");
            return (Criteria) this;
        }

        public Criteria andWordCountNotBetween(Long value1, Long value2) {
            addCriterion("word_count not between", value1, value2, "wordCount");
            return (Criteria) this;
        }

        public Criteria andClickNumberIsNull() {
            addCriterion("click_number is null");
            return (Criteria) this;
        }

        public Criteria andClickNumberIsNotNull() {
            addCriterion("click_number is not null");
            return (Criteria) this;
        }

        public Criteria andClickNumberEqualTo(Long value) {
            addCriterion("click_number =", value, "clickNumber");
            return (Criteria) this;
        }

        public Criteria andClickNumberNotEqualTo(Long value) {
            addCriterion("click_number <>", value, "clickNumber");
            return (Criteria) this;
        }

        public Criteria andClickNumberGreaterThan(Long value) {
            addCriterion("click_number >", value, "clickNumber");
            return (Criteria) this;
        }

        public Criteria andClickNumberGreaterThanOrEqualTo(Long value) {
            addCriterion("click_number >=", value, "clickNumber");
            return (Criteria) this;
        }

        public Criteria andClickNumberLessThan(Long value) {
            addCriterion("click_number <", value, "clickNumber");
            return (Criteria) this;
        }

        public Criteria andClickNumberLessThanOrEqualTo(Long value) {
            addCriterion("click_number <=", value, "clickNumber");
            return (Criteria) this;
        }

        public Criteria andClickNumberIn(List<Long> values) {
            addCriterion("click_number in", values, "clickNumber");
            return (Criteria) this;
        }

        public Criteria andClickNumberNotIn(List<Long> values) {
            addCriterion("click_number not in", values, "clickNumber");
            return (Criteria) this;
        }

        public Criteria andClickNumberBetween(Long value1, Long value2) {
            addCriterion("click_number between", value1, value2, "clickNumber");
            return (Criteria) this;
        }

        public Criteria andClickNumberNotBetween(Long value1, Long value2) {
            addCriterion("click_number not between", value1, value2, "clickNumber");
            return (Criteria) this;
        }

        public Criteria andAddRackIsNull() {
            addCriterion("add_rack is null");
            return (Criteria) this;
        }

        public Criteria andAddRackIsNotNull() {
            addCriterion("add_rack is not null");
            return (Criteria) this;
        }

        public Criteria andAddRackEqualTo(Long value) {
            addCriterion("add_rack =", value, "addRack");
            return (Criteria) this;
        }

        public Criteria andAddRackNotEqualTo(Long value) {
            addCriterion("add_rack <>", value, "addRack");
            return (Criteria) this;
        }

        public Criteria andAddRackGreaterThan(Long value) {
            addCriterion("add_rack >", value, "addRack");
            return (Criteria) this;
        }

        public Criteria andAddRackGreaterThanOrEqualTo(Long value) {
            addCriterion("add_rack >=", value, "addRack");
            return (Criteria) this;
        }

        public Criteria andAddRackLessThan(Long value) {
            addCriterion("add_rack <", value, "addRack");
            return (Criteria) this;
        }

        public Criteria andAddRackLessThanOrEqualTo(Long value) {
            addCriterion("add_rack <=", value, "addRack");
            return (Criteria) this;
        }

        public Criteria andAddRackIn(List<Long> values) {
            addCriterion("add_rack in", values, "addRack");
            return (Criteria) this;
        }

        public Criteria andAddRackNotIn(List<Long> values) {
            addCriterion("add_rack not in", values, "addRack");
            return (Criteria) this;
        }

        public Criteria andAddRackBetween(Long value1, Long value2) {
            addCriterion("add_rack between", value1, value2, "addRack");
            return (Criteria) this;
        }

        public Criteria andAddRackNotBetween(Long value1, Long value2) {
            addCriterion("add_rack not between", value1, value2, "addRack");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_detail
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_detail
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}