package cn.longzzai.pojo;

public class MajorCate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_cate.major_cate_id
     *
     * @mbggenerated
     */
    private Integer majorCateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_cate.major_cate_name
     *
     * @mbggenerated
     */
    private String majorCateName = "未分类";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_cate.major_cate_sex
     *
     * @mbggenerated
     */
    private Byte majorCateSex = 0;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_cate.major_cate_id
     *
     * @return the value of major_cate.major_cate_id
     *
     * @mbggenerated
     */
    public Integer getMajorCateId() {
        return majorCateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_cate.major_cate_id
     *
     * @param majorCateId the value for major_cate.major_cate_id
     *
     * @mbggenerated
     */
    public void setMajorCateId(Integer majorCateId) {
        this.majorCateId = majorCateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_cate.major_cate_name
     *
     * @return the value of major_cate.major_cate_name
     *
     * @mbggenerated
     */
    public String getMajorCateName() {
        return majorCateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_cate.major_cate_name
     *
     * @param majorCateName the value for major_cate.major_cate_name
     *
     * @mbggenerated
     */
    public void setMajorCateName(String majorCateName) {
        this.majorCateName = majorCateName == null ? null : majorCateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_cate.major_cate_sex
     *
     * @return the value of major_cate.major_cate_sex
     *
     * @mbggenerated
     */
    public Byte getMajorCateSex() {
        return majorCateSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_cate.major_cate_sex
     *
     * @param majorCateSex the value for major_cate.major_cate_sex
     *
     * @mbggenerated
     */
    public void setMajorCateSex(Byte majorCateSex) {
        this.majorCateSex = majorCateSex;
    }
}