package cn.longzzai.pojo;

public class MinorCate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minor_cate.minor_cate_id
     *
     * @mbggenerated
     */
    private Integer minorCateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minor_cate.minor_cate_name
     *
     * @mbggenerated
     */
    private String minorCateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minor_cate.major_cate_name
     *
     * @mbggenerated
     */
    private String majorCateName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minor_cate.minor_cate_id
     *
     * @return the value of minor_cate.minor_cate_id
     *
     * @mbggenerated
     */
    public Integer getMinorCateId() {
        return minorCateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minor_cate.minor_cate_id
     *
     * @param minorCateId the value for minor_cate.minor_cate_id
     *
     * @mbggenerated
     */
    public void setMinorCateId(Integer minorCateId) {
        this.minorCateId = minorCateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minor_cate.minor_cate_name
     *
     * @return the value of minor_cate.minor_cate_name
     *
     * @mbggenerated
     */
    public String getMinorCateName() {
        return minorCateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minor_cate.minor_cate_name
     *
     * @param minorCateName the value for minor_cate.minor_cate_name
     *
     * @mbggenerated
     */
    public void setMinorCateName(String minorCateName) {
        this.minorCateName = minorCateName == null ? null : minorCateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minor_cate.major_cate_name
     *
     * @return the value of minor_cate.major_cate_name
     *
     * @mbggenerated
     */
    public String getMajorCateName() {
        return majorCateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minor_cate.major_cate_name
     *
     * @param majorCateName the value for minor_cate.major_cate_name
     *
     * @mbggenerated
     */
    public void setMajorCateName(String majorCateName) {
        this.majorCateName = majorCateName == null ? null : majorCateName.trim();
    }
}