package cn.longzzai.pojo;

import java.util.ArrayList;
import java.util.List;

public class MinorCateExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    public MinorCateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMinorCateIdIsNull() {
            addCriterion("minor_cate_id is null");
            return (Criteria) this;
        }

        public Criteria andMinorCateIdIsNotNull() {
            addCriterion("minor_cate_id is not null");
            return (Criteria) this;
        }

        public Criteria andMinorCateIdEqualTo(Integer value) {
            addCriterion("minor_cate_id =", value, "minorCateId");
            return (Criteria) this;
        }

        public Criteria andMinorCateIdNotEqualTo(Integer value) {
            addCriterion("minor_cate_id <>", value, "minorCateId");
            return (Criteria) this;
        }

        public Criteria andMinorCateIdGreaterThan(Integer value) {
            addCriterion("minor_cate_id >", value, "minorCateId");
            return (Criteria) this;
        }

        public Criteria andMinorCateIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("minor_cate_id >=", value, "minorCateId");
            return (Criteria) this;
        }

        public Criteria andMinorCateIdLessThan(Integer value) {
            addCriterion("minor_cate_id <", value, "minorCateId");
            return (Criteria) this;
        }

        public Criteria andMinorCateIdLessThanOrEqualTo(Integer value) {
            addCriterion("minor_cate_id <=", value, "minorCateId");
            return (Criteria) this;
        }

        public Criteria andMinorCateIdIn(List<Integer> values) {
            addCriterion("minor_cate_id in", values, "minorCateId");
            return (Criteria) this;
        }

        public Criteria andMinorCateIdNotIn(List<Integer> values) {
            addCriterion("minor_cate_id not in", values, "minorCateId");
            return (Criteria) this;
        }

        public Criteria andMinorCateIdBetween(Integer value1, Integer value2) {
            addCriterion("minor_cate_id between", value1, value2, "minorCateId");
            return (Criteria) this;
        }

        public Criteria andMinorCateIdNotBetween(Integer value1, Integer value2) {
            addCriterion("minor_cate_id not between", value1, value2, "minorCateId");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameIsNull() {
            addCriterion("minor_cate_name is null");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameIsNotNull() {
            addCriterion("minor_cate_name is not null");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameEqualTo(String value) {
            addCriterion("minor_cate_name =", value, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameNotEqualTo(String value) {
            addCriterion("minor_cate_name <>", value, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameGreaterThan(String value) {
            addCriterion("minor_cate_name >", value, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameGreaterThanOrEqualTo(String value) {
            addCriterion("minor_cate_name >=", value, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameLessThan(String value) {
            addCriterion("minor_cate_name <", value, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameLessThanOrEqualTo(String value) {
            addCriterion("minor_cate_name <=", value, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameLike(String value) {
            addCriterion("minor_cate_name like", value, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameNotLike(String value) {
            addCriterion("minor_cate_name not like", value, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameIn(List<String> values) {
            addCriterion("minor_cate_name in", values, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameNotIn(List<String> values) {
            addCriterion("minor_cate_name not in", values, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameBetween(String value1, String value2) {
            addCriterion("minor_cate_name between", value1, value2, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andMinorCateNameNotBetween(String value1, String value2) {
            addCriterion("minor_cate_name not between", value1, value2, "minorCateName");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameIsNull() {
            addCriterion("major_cate_name is null");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameIsNotNull() {
            addCriterion("major_cate_name is not null");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameEqualTo(String value) {
            addCriterion("major_cate_name =", value, "majorCateName");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameNotEqualTo(String value) {
            addCriterion("major_cate_name <>", value, "majorCateName");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameGreaterThan(String value) {
            addCriterion("major_cate_name >", value, "majorCateName");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameGreaterThanOrEqualTo(String value) {
            addCriterion("major_cate_name >=", value, "majorCateName");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameLessThan(String value) {
            addCriterion("major_cate_name <", value, "majorCateName");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameLessThanOrEqualTo(String value) {
            addCriterion("major_cate_name <=", value, "majorCateName");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameLike(String value) {
            addCriterion("major_cate_name like", value, "majorCateName");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameNotLike(String value) {
            addCriterion("major_cate_name not like", value, "majorCateName");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameIn(List<String> values) {
            addCriterion("major_cate_name in", values, "majorCateName");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameNotIn(List<String> values) {
            addCriterion("major_cate_name not in", values, "majorCateName");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameBetween(String value1, String value2) {
            addCriterion("major_cate_name between", value1, value2, "majorCateName");
            return (Criteria) this;
        }

        public Criteria andMajorCateNameNotBetween(String value1, String value2) {
            addCriterion("major_cate_name not between", value1, value2, "majorCateName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table minor_cate
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}