package cn.longzzai.mapper;

import cn.longzzai.pojo.MajorCate;
import cn.longzzai.pojo.MajorCateExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MajorCateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_cate
     *
     * @mbggenerated
     */
    int countByExample(MajorCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_cate
     *
     * @mbggenerated
     */
    int deleteByExample(MajorCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_cate
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer majorCateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_cate
     *
     * @mbggenerated
     */
    int insert(MajorCate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_cate
     *
     * @mbggenerated
     */
    int insertSelective(MajorCate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_cate
     *
     * @mbggenerated
     */
    List<MajorCate> selectByExample(MajorCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_cate
     *
     * @mbggenerated
     */
    MajorCate selectByPrimaryKey(Integer majorCateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_cate
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MajorCate record, @Param("example") MajorCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_cate
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MajorCate record, @Param("example") MajorCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_cate
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MajorCate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major_cate
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MajorCate record);
}