package cn.longzzai.mapper;

import cn.longzzai.pojo.MinorCate;
import cn.longzzai.pojo.MinorCateExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MinorCateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    int countByExample(MinorCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    int deleteByExample(MinorCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer minorCateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    int insert(MinorCate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    int insertSelective(MinorCate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    List<MinorCate> selectByExample(MinorCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    MinorCate selectByPrimaryKey(Integer minorCateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MinorCate record, @Param("example") MinorCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MinorCate record, @Param("example") MinorCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MinorCate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table minor_cate
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MinorCate record);
}